@echo off
echo ========================================
echo Document Management System - Frontend
echo ========================================

REM ===========================================
REM CONFIGURATION - AUTO-GENERATED BY SETUP
REM ===========================================

REM Network Configuration
set YOUR_COMPUTER_IP={{COMPUTER_IP}}
set API_URL=http://{{COMPUTER_IP}}:{{BACKEND_PORT}}/api
set APP_NAME={{APP_NAME}}
set FRONTEND_PORT={{FRONTEND_PORT}}

REM ===========================================
REM DO NOT EDIT BELOW THIS LINE
REM ===========================================

echo Configuration:
echo - API URL: %API_URL%
echo - Frontend Port: %FRONTEND_PORT%
echo - Your IP: %YOUR_COMPUTER_IP%
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ❌ Node.js is not installed!
    echo Please download and install Node.js from: https://nodejs.org/
    pause
    exit /b 1
)

REM Check if npm is installed
where npm >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ❌ npm is not installed!
    echo Please install npm (usually comes with Node.js)
    pause
    exit /b 1
)

REM Configure runtime environment
echo Configuring for network access...

REM Update the env.js file with the correct API URL
echo (function (window) { > assets\env.js
echo   window["env"] = window["env"] ^|^| {}; >> assets\env.js
echo   window["env"]["apiUrl"] = "%API_URL%"; >> assets\env.js
echo   window["env"]["appName"] = "%APP_NAME%"; >> assets\env.js
echo   window["env"]["version"] = "1.0.0"; >> assets\env.js
echo })(this); >> assets\env.js

echo ✅ Configuration updated!
echo.

REM Install http-server if not available globally
echo Checking for http-server...
where http-server >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo Installing http-server...
    call npm install -g http-server
)

echo Starting frontend server...
echo ========================================
echo.
echo Frontend will be available at:
echo   Local: http://localhost:%FRONTEND_PORT%
echo   Network: http://%YOUR_COMPUTER_IP%:%FRONTEND_PORT%
echo.
echo Make sure your backend is running at: %API_URL%
echo.
echo Press Ctrl+C to stop the server
echo ========================================

REM Start the server with network access
call npx http-server . -p %FRONTEND_PORT% -a 0.0.0.0 --cors

if %ERRORLEVEL% neq 0 (
    echo.
    echo ❌ Failed to start the frontend server!
    echo.
    echo Alternative: Try running this manually:
    echo   npx http-server . -p %FRONTEND_PORT% -a 0.0.0.0 --cors
    pause
) 